<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OnMuhasebe.Core\OnMuhasebe.Core.csproj" />
    <ProjectReference Include="..\OnMuhasebe.Entities\OnMuhasebe.Entities.csproj" />
    <ProjectReference Include="..\OnMuhasebe.DataAccess\OnMuhasebe.DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.*" />
  </ItemGroup>
  <ItemGroup>
  <FrameworkReference Include="Microsoft.AspNetCore.App" />
</ItemGroup> 

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
